version: '3'

services:
  api:
    build: .
    ports:
      - '8081:8081'
    depends_on:
      - mysql
      - mailpit
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
    networks:
      - default
      - sleeved-network
    container_name: warden-api

  mysql:
    image: mysql:8
    ports:
      - '3310:3306'
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mysql-data:

networks:
  default:
  sleeved-network:
    external: true
