version: '3'

services:
  app:
    build: .
    ports:
      - '0.0.0.0:3310:3333'
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build

  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=warden
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
