version: '3'

services:
  api:
    build: .
    ports:
      - '0.0.0.0:8081:8081'
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build

  mysql:
    image: mysql:8
    ports:
      - '3310:3306'
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
