version: '3'

services:
  app:
    build: .
    ports:
      - '3333:3333'
    depends_on:
      - mysql
    environment:
      - TZ=UTC
      - PORT=3333
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=${APP_KEY}
      - NODE_ENV=development
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=warden

  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=warden
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
