version: '3'

tasks:
  default:
    desc: Display available commands
    cmds:
      - task --list-all
    silent: true

  # Database commands
  db:migrate:
    desc: Run database migrations
    cmds:
      - docker compose exec api node ace migration:run

  db:rollback:
    desc: Rollback the last migration
    cmds:
      - docker compose exec api node ace migration:rollback

  db:migration:
    desc: Create a new migration
    cmds:
      - docker compose exec api node ace make:migration {{.CLI_ARGS}}
    requires:
      vars: [CLI_ARGS]

  db:seed:
    desc: Run database seeders
    cmds:
      - docker compose exec api node ace db:seed

  # Application commands
  start:
    desc: Start all services
    cmds:
      - docker compose up -d

  stop:
    desc: Stop all services
    cmds:
      - docker compose down {{.CLI_ARGS}}

  restart:
    desc: Restart all services
    cmds:
      - task: stop
      - task: start

  build:
    desc: Build the application
    cmds:
      - docker compose build {{.CLI_ARGS}}

  rebuild:
    desc: Rebuild and restart
    cmds:
      - task: stop
      - task: build
      - task: start
      - task: logs

  logs:
    desc: Show application logs
    cmds:
      - docker compose logs -f api

  shell:
    desc: Open a shell in the api container
    cmds:
      - docker compose exec api /bin/sh

  # Development commands
  test:
    desc: Run tests (optional args - use test:unit or test:functional for specific suites)
    cmds:
      - docker compose exec api node ace test {{.CLI_ARGS}}

  test:unit:
    desc: Run unit tests only
    cmds:
      - docker compose exec api node ace test unit {{.CLI_ARGS}}

  test:functional:
    desc: Run functional tests only
    cmds:
      - docker compose exec api node ace test functional {{.CLI_ARGS}}

  lint:
    desc: Run linting
    cmds:
      - docker compose exec api npm run lint

  format:
    desc: Format code
    cmds:
      - docker compose exec api npm run format
